#include <stdio.h>
#include <ncurses.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <string.h>

#include "stageOne.h"
#include "stageTwo.h"
#include "stageThree.h"
#include "stageFour.h"
#include "stageFive.h"
#include "stageSix.h"
#include "stageSeven.h"
#include "stageEight.h"
#include "stageNine.h"
#include "stageTen.h"
#include "soundPlayer.h"
#include "safeFunctions.h"
